#pragma once

#include <map>

//※※※ 重要!! ※※※※※※※※※
//※※※ 錯誤代碼請用新增，勿修改或刪除原有的代碼

namespace GMT
{
	class MessageTable
	{
	public:
		static std::string Get(int code)
		{
			return messageMap.at(code);
		}
	
	private:
		static const std::map<int, std::string> messageMap;
	};
	
//1xxxxxx generic
#define MESSAGE_OK 11001
#define MESSAGE_INPUT_ILLEGAL 11002

//2xxxxxx trajctory
#define MESSAGE_TRAJCTORY_NORMAL_END 12001
#define MESSAGE_TRAJCTORY_K_OUT_OF_RANGE 12002
#define MESSAGE_TRAJCTORY_NOT_INITIALED 12003
#define MESSAGE_TRAJCTORY_N_IS_NAN 12004
#define MESSAGE_TRAJCTORY_SPIRAL_OPTION_TYPE_UNKNOW 12005
#define MESSAGE_TRAJCTORY_SPIRAL_P_OUT_OF_SCAN_RANGE 12006

//3xxxxxx stewart basic
#define MESSAGE_TOOL_TRAJCTORY_START_OUT_OF_RANGE 13001
#define MESSAGE_TOOL_TRAJCTORY_END_OUT_OF_RANGE 13002
#define MESSAGE_TOOL_TRAJCTORY_EMPTY 13003
#define MESSAGE_TOOL_N_IK_FAIL_POSE_CANT_BE_REACHED 13004
#define MESSAGE_TOOL_TRAJCTORY_P_OUT_OF_MACHINE_WORKING_RANGE 13005
#define MESSAGE_TOOL_TRAJCTORY_SPIRAL_END 13006
#define MESSAGE_TOOL_STAGE_ERROR 13007
#define MESSAGE_TOOL_STEWART_TYPE_ERROR 13008
#define MESSAGE_TOOL_SCAN_OUT_OF_RANGE 13009
#define MESSAGE_TOOL_STEP_OUT_OF_RANGE 13010
#define MESSAGE_TOOL_SIN_OUT_OF_RANGE 13011
#define MESSAGE_TOOL_WS_SCAN_FAIL 13012

#define SPIRAL_STAGE_START_SPIRAL 14001
#define SPIRAL_STAGE_SPIRAL_END_BACK_TO_START 14002

#define SIN_STAGE_START_TO_SIN 14003
#define SIN_STAGE_SIN 14004
#define SIN_STAGE_SIN_END_TO_START 14005

#define MESSAGE_FA_MAX_FOUND 15001
#define MESSAGE_FA_BETWEEN_THD0_THD1 15002
#define MESSAGE_FA_BELOW_THD0 15003
#define MESSAGE_FA_SET_THRESHOLD 15004
#define MESSAGE_FA_LIGHT_SOURCE_ERROR 15005
#define MESSAGE_FA_LIGHT_SOURCE_NONUSE 15006

};